config/routes.rb
Rails.application.routes.draw do

  root 'movies#index', as: :home
  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do 
    resources :users
  end
    resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  get 'sessions/switch/:id' => "sessions#switch_to_user"

  get 'sessions/switch-back' => "sessions#switch_to_admin"

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: {only_integer: true}
  validates :description, presence: true
  validates :release_date, presence: true
  validates :image, presence: true
  validate :release_date_is_in_the_past

  def review_average
    (reviews.sum(:rating_out_of_ten).to_f / reviews.size).round(2) if reviews.size > 0
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end 
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true

  validates :movie, presence: true

  validates :text, presence: true

  validates :rating_out_of_ten, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10  }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  validates :email, presence: true
  validates :firstname, presence: true
  validates :password, length: {in: 6..20}, on: :create
  has_secure_password

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :is_admin?
    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end

    def new 
      @user = User.new
    end

    def create 
      @user = User.new(user_params)
      if @user.save
        flash[:notice] = "#{@user.full_name} is created!"
        redirect_to admin_users_path
      else
        render :new
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:notice] = "#{@user.full_name} profile is updated successfully"
        redirect_to admin_users_path
      else
        render :edit
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      UserMailer.account_deleted_email(@user).deliver_now
      flash[:notice] = "#{@user.full_name} deleted!"
      redirect_to admin_users_path
    end

    private

    def is_admin?
      unless current_user && current_user.is_admin
        flash[:alert] = "unauthorized access denied!"
        redirect_to home_path 
      end
    end

    def user_params
      params.require(:user).permit(:email, :firstname, :lastname, :is_admin, :password, :password_confirmation)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in"
      redirect_to new_session_path
    end
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index

    @movies = Movie.all

    if params[:title]
      @movies = @movies.where("title LIKE ? AND director LIKE ? OR runtime_in_minutes LIKE ?", "%#{params[:title]}%", "%#{params[:director]}%", "%#{params[:runtime_in_minutes]}%")
    end
    if params[:director]
      @movies = @movies.where("director LIKE ?", "%#{params[:director]}%")
    end
    if params[:runtime_in_minutes]
      if params[:runtime_in_minutes] == "90"
        @movies = @movies.where("runtime_in_minutes < ?", "%#{params[:runtime_in_minutes]}%")
      elsif params[:runtime_in_minutes] == "120"
        @movies = @movies.where("runtime_in_minutes > ?", "%#{params[:runtime_in_minutes]}%")
      else
        minutes = params[:runtime_in_minutes].split('-')
        @movies = @movies.where("runtime_in_minutes BETWEEN ? and ?", "%#{minutes[0].to_i}%", "%#{minutes[1].to_i}%" )
      end
    end

  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy 
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :release_date, :director, :runtime_in_minutes, :image, :remove_image, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie, :restrict_access

  def new
    # @review = Review.new(movie_id: @movie.id)
    @review = @movie.reviews.build #same as above but more concise
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  private

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "email and password combination is not correct"
      render :new

    end
  end

  def switch_to_user
    if current_user && current_user.is_admin
      session[:admin_user_id] = current_user.id
      session[:user_id] = params[:id]
      redirect_to home_path
    else
      render html: 'not authorized'
    end
  end

  def switch_to_admin
    if current_user
      if session[:admin_user_id]
        session[:user_id] = session[:admin_user_id]
        session[:admin_user_id] = nil
      end
      redirect_to home_path
    else
      render html: 'not authorized'
    end
  end


  def destroy
    session[:user_id] = nil
    session[:admin_user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome abroad, #{@user.firstname}!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>Edit User</h2>
 
 <% if @user.errors.present? %> 
 <div>
 <%= pluralize(@user.errors.count, "errors") %> prevented this movie from being submitted:
 <ul>
<% @user.errors.full_messages.each do |error| %>
  <li><%= error %></li>
<% end %>
</ul>
</div>
 <% end %>
<%= form_for @user, url: admin_user_path(@user) do |f| %>

  <div>
    <%= f.label :email, "Email" %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, "Password confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
    <div>
    <%= f.label :is_admin, "set as admin" %>
    <%= f.check_box :is_admin %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/admin/users/index.html.erb
<h2>Admin User Management</h2>
<div style="margin-bottom: 30px;">
  <%= link_to("Create new user", new_admin_user_path) %>
</div>
<% @users.each do |user| %>
  <% unless user == current_user %>
  <div style="margin-bottom: 20px;">
    <span><%= user.full_name %></span>
    <%= link_to("profile", admin_user_path(user)) %> 
    <%= link_to 'edit', edit_admin_user_path(user) %>
    <%= link_to 'delete', admin_user_path(user), method: :delete, data: {confirm: "You sure?"} %>
    <%= link_to 'switch', "/sessions/switch/#{user.id}" %>
  </div>
  <% end %>
<% end %>

app/views/admin/users/new.html.erb
<h2>Create User</h2>
 
 <% if @user.errors.present? %> 
 <div>
 <%= pluralize(@user.errors.count, "errors") %> prevented this movie from being submitted:
 <ul>
<% @user.errors.full_messages.each do |error| %>
  <li><%= error %></li>
<% end %>
</ul>
</div>
 <% end %>
<%= form_for @user, url: admin_users_path do |f| %>

  <div>
    <%= f.label :email, "Email" %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, "Password confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :is_admin, "set as admin" %>
    <%= f.check_box :is_admin %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/admin/users/show.html.erb
<h2><%= @user.full_name %></h2>
<p><%= @user.email %></p>
<p>admin: <%= @user.is_admin %></p>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path('current'), method: :delete %>)
       <% if current_user.is_admin %>
          <%= link_to("admin", admin_users_path) %>
       <% end %>
    <% else %>
      <%= link_to("Log in", new_session_path) %> | <%= link_to("Sign Up", new_user_path)  %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if session[:admin_user_id] %>
   <%= link_to("back to admin", "/sessions/switch-back") %>
<% end %>

<% flash.each do |message_type, message| %>
     <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
 <% end %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/movies/_form.html.erb
 
 <% if @movie.errors.present? %> 
 <div>
 <%= pluralize(@movie.errors.count, "errors") %> prevented this movie from being submitted:
 <ul>
<% @movie.errors.full_messages.each do |error| %>
  <li><%= error %></li>
<% end %>
</ul>
</div>
 <% end %>
 <%= form_for @movie, html: {multipart: true} do |f| %>
      <div>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :release_date %><br>
        <%= f.date_field :release_date %>
      </div>
      <div>
        <%= f.label :director %><br>
        <%= f.text_field :director %>
      </div>
      <div>
        <%= f.label :runtime_in_minutes %><br>
        <%= f.number_field :runtime_in_minutes %>
      </div>
      <div>
        <%= f.label :image %><br>
        <%= f.file_field :image %>
        <% if f.object.image? %>
          <%= image_tag f.object.image.thumb.url %>
          <%= f.label :remove_image %>
          <%= f.check_box :remove_image %> 
        <% end %>
      </div>
      <div>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
      <div>
        <%= f.submit "Submit" %> 
      </div>
    <% end %>

app/views/movies/edit.html.erb
   <%= link_to "Back to this movie", movie_path(@movie) %>

    <h2>Edit this movie.</h2>
   
   <%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%=link_to "Submit a movie", new_movie_path %>
<hr>

<%= form_tag movies_path ,method: :get do %>
  <div class="col-lg-2">
    <%= label_tag :title, "Title" %>
    <%= text_field_tag :title %>
  </div>
  <div>
    <%= label_tag :director %>
    <%= text_field_tag :director %>
  </div>
  <div>
    <%= label_tag :runtime_in_minutes %>
    <%= select_tag(:runtime_in_minutes, options_for_select([["under 90 minutes", 90],["between 90 and 120 minutes", "90-120"],["more than 120 minutes", 120]], 1)) %>
  </div>
  <div>
    <%= submit_tag "Submit"%>
  </div>
<% end %>

<% @movies.each do |movie| %>
  <div><%=image_tag(movie.image.thumb.url)%></div>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <h4><%= movie.review_average %></h4>
  <p><%= movie.description%></p>
  <hr>
<% end %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>
<h2>Submit a movie</h2>

<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.image.thumb.url), movie_path(@movie) %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, data: {confirm: "You sure?"} %>)</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<h4>Average score: <%= @movie.review_average %></h4>
<p><%= @movie.description %></p>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  
    <% @movie.reviews.each do |review| %>
      <p><%= review.text %></p>
      <p><%= review.rating_out_of_ten %>/10</p>
      <small>- <%= review.user.full_name %></small><br>
    <% end %>

    <p><%= link_to("Write a review!", new_movie_review_path(@movie)) %></p>
  <% else %>
    <p>Please <%= link_to("log in", new_session_path) %> to see reviews and add your own.</p>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br>
<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div>
        <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
        <ul>
          <% @review.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div>
        <%= f.label :text %>
        <%= f.text_area "text" %>
      </div>
      <div>
        <%= f.label :rating_out_of_ten %><br>
        <%= f.number_field :rating_out_of_ten %>
      </div>
      <div>
        <%= f.submit "Submit" %>
      </div>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div>
    <%= pluralize(@user.errors.count, "errors") %> prevented the account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div>
    <%= f.label :email, "Email" %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, "Password confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>

  <% end %>